### ISSUE TITLE
Health tab- indicators not showing up

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#11]
Life expectancy, mortality rate, infant mortality rate are not displaying for any geography. Only EBLL is displaying. 

![image](https://user-images.githubusercontent.com/7606957/51406539-790bc600-1b27-11e9-89a3-fcddaba5254c.png)

**Comment by bormesh** [comment]
All health tab indicators are now displaying correctly.

**Comment by bormesh** [comment]
Random Question -- is this infant mortality rate correct for Cuyahoga Valley? Small sample size?

![image](https://user-images.githubusercontent.com/2038993/51564024-120a4c00-1e5c-11e9-9ab9-a22d0a6f6b35.png)
