### ISSUE TITLE
Health tab- EBLL not displaying for Cleveland and Cuyahoga geographies

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#12]
Elevated blood lead level indicator not displaying for City of Cleveland, Cuyahoga County, or _ Cleveland and _ Cuyahoga (underneath neighborhood geographies). 

![image](https://user-images.githubusercontent.com/7606957/51406726-f0d9f080-1b27-11e9-8c17-83abb685ded6.png)

![image](https://user-images.githubusercontent.com/7606957/51406758-02bb9380-1b28-11e9-937d-64f93646cc36.png)

**Comment by bormesh** [comment]
Cleveland and Cuyahoga County are now displaying correctly.
