### ISSUE TITLE
Workforce tab- tables not displaying for Cleveland, county, _cleveland and _county geographies

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#13]
Indicators are not displaying in the workforce tab for the Cleveland city, Cuyahoga County, _ Cleveland, and _ Cuyahoga geographies

![image](https://user-images.githubusercontent.com/7606957/51407012-c50b3a80-1b28-11e9-9c3e-e9a74c9fa744.png)

![image](https://user-images.githubusercontent.com/7606957/51407040-d7857400-1b28-11e9-951d-98e765f32a17.png)

**Comment by bormesh** [comment]
Workforce now functions for Cleveland and Cuyahoga County.
![image](https://user-images.githubusercontent.com/2038993/51498456-909bb680-1d94-11e9-827a-eac2af39754f.png)
