### ISSUE TITLE
Economy tab- indicators not displaying for City of Cleveland, Cuyahoga County, _Cleveland, and _Cuyahoga geographies

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#14]
Indicators are not displaying for City of Cleveland, Cuyahoga County, _Cleveland, and _County geographies.

![image](https://user-images.githubusercontent.com/7606957/51407912-2b915800-1b2b-11e9-9558-2539f84ecb38.png)

![image](https://user-images.githubusercontent.com/7606957/51407945-3fd55500-1b2b-11e9-8165-4a0cc3c40bc2.png)

![image](https://user-images.githubusercontent.com/7606957/51407965-4f549e00-1b2b-11e9-8cbf-7fe4c44f3314.png)

![image](https://user-images.githubusercontent.com/7606957/51407994-5f6c7d80-1b2b-11e9-8dfc-e1454d60eaf8.png)

**Comment by bormesh** [comment]
![image](https://user-images.githubusercontent.com/2038993/51497825-60ebaf00-1d92-11e9-99a4-588c6eb9986c.png)

Data should be displaying now. Commercial Rent Data is updated but Number of Jobs is not updated. Should _Cleveland and _Cuyahoga have data? I believe those locations should be hidden.

**Comment by aprilhirsh** [comment]
Data is displaying now for all geographic levels. 
The latest date for the number of jobs figure is 2015, so that it displaying correctly.
Both indicators should have values for the City of Cleveland and Cuyahoga County.
_Cuyahoga and __Cleveland Municipal School District show up as geographies under the "neighborhood" group, but that is a separate issue.
