### ISSUE TITLE
Education tab- Kindergarten Readiness Assessment- Level- table name change

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#15]
In the education tab, the table labeled 

Kindergarten Readiness Assessment Level (KRA-L)

should be changed to 

Kindergarten Readiness Assessment- Literacy (KRA-L)

**Comment by bormesh** [comment]
This is fixed.

**Comment by aprilhirsh** [comment]
It currently reads:
Kindergarten Readiness Assessment Level- Literacy (KRA-L)

It should read:

Kindergarten Readiness Assessment- Literacy (KRA-L)

Please remove "level"

**Comment by bormesh** [comment]
Ok, Level has been removed as well.
