### ISSUE TITLE
Foreclosure Data Load

### ISSUE THREAD

**Issue by bormesh** [PovertyCenterCLE/Progress_Index_Bugs#16]
Figure out why foreclosure CSVs are not loading

![image](https://user-images.githubusercontent.com/2038993/51466654-b004f600-1d38-11e9-9c1c-8f30c8323d34.png)

Might have to do with rev_... at end of file.

**Comment by aprilhirsh** [comment]
I reloaded the file with the correct name.

**Comment by bormesh** [comment]
Sounds good -- I'll close this then if you didn't get the error again?
