### ISSUE TITLE
Education tab- latest school year not populating

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#17]
I think this is a variable name to label issue. I'm consulting with Tsui on whether the year represents the beginning or end of the school year.
Ex: rpassed32013 = 2012-2013 school year or 2013-2014 school year.

**Comment by aprilhirsh** [comment]
The year reflects the end of the school year
2013 = 2012-2013 school year
2014 = 2013-2014 school year
2015 = 2014-2015 school year
2016 = 2015-2016 school year
2017 = 2016-2017 school year

These are the 5 time points that should be reflected in the education tab. Currently, the 2017-2018 year is displaying, but is blank. I'm not sure why.

![image](https://user-images.githubusercontent.com/7606957/51568566-00c73c80-1e68-11e9-9623-d854a09cd465.png)

**Comment by bormesh** [comment]
Ok, that makes sense. 

@aprilhirsh In the Dashboard, you'll have to update the 'school year' time range to reflect this. Right now, we have start time 2012, end time 2016. But since we're dealing with the end of the year, then it should be 2013, 2017.

Thanks!

**Comment by bormesh** [comment]
I've updated the tables header accordingly.

**Comment by aprilhirsh** [comment]
I've updated the variable list, but can not upload it, because of #20

**Comment by bormesh** [comment]
School year labels now look correct with #20 being fixed.

**Comment by aprilhirsh** [comment]
Data not displaying for Cleveland. I'm assuming it's because I renamed the _Cleveland municipal school district geography to Cleveland city? I'll try changing the name back to what it was and uploading again.

**Comment by aprilhirsh** [comment]
Still doesn't show for geographic level = city, location = cleveland. Screen shot below. But it DOES show for geographic level = all, location = cleveland city. Screen shot also below.

Other tabs that will load data when this geography (level = all, location = cleveland city) is selected:
Portions of overview tab
Population tab (without headers)
Health (also without headers)

All other tabs don't load data when this geography is selected.

Is this something that we need to fix on our end? Let us know what you think.

![image](https://user-images.githubusercontent.com/7606957/51722026-010b3780-2022-11e9-95a0-1fad004daff0.png)


![image](https://user-images.githubusercontent.com/7606957/51722009-eb960d80-2021-11e9-86b9-98ddb36d16c5.png)
