### ISSUE TITLE
Geographies underneath neighborhood geo group that shouldn't be there

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#18]
My guess is that these are coming from the CMSD files. Let me know if you think that's correct.

I can't take a screen shot of these because they're in the drop down menu, but to replicate, in the "select a location" box choose "neighborhood" under "level" and then in the "location" box scroll all the way to the bottom to see _ Cuyahoga and __ Cleveland Municipal School District.

I'm going to confer with Tsui on what we should do about these.

**Comment by aprilhirsh** [comment]
I removed _Suburbs and _Unknown and renamed _Cleveland Municipal School District to Cleveland city. I'm going to do another upload and see if that solves this issue. Let me know if I'm not interpreting that right (_Cleveland Municipal School district = Cleveland city)

**Comment by aprilhirsh** [comment]
When I tried to do a new upload, the system didn't seem to do the upload. I'm on my home network, so I'll try again tomorrow on the CWRU network.

**Comment by tsuichan** [comment]
This looks like the same issue as the one I just submitted on the Location drop down menu.  I'm going to close this.
