### ISSUE TITLE
Stabilization tab- add eviction table

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#19]
We need to add the new eviction table. It should go in the Stabilization tab. 

Variable names:
evict
move_out
_evict
_move_out

Years are 2012-2016, time type is yearly

Labels are:
evict- Eviction cases filed
move_out- Eviction cases- move-outs performed
_evict- Eviction cases filed, rate per rental housing units
_move_out- Eviction cases- move-outs performed, rate per rental housing units

Everything is in the varlist document.

**Comment by bormesh** [comment]
This will be added by tomorrow morning.

**Comment by bormesh** [comment]
Need to get the columns correct, but the table now exists.

**Comment by aprilhirsh** [comment]
Could we format the rates to be 1 decimal? Example: 10.1%

**Comment by aprilhirsh** [comment]
Looks like this is done
