### ISSUE TITLE
I broke the upload function- now many other things look broke too

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#20]
Data upload is only uploading three files, then sending the message that it is complete. This is the same issue I ran into yesterday, but yesterday I thought my wireless network was the culprit, so didn't report it. I think it has caused some of the data to no longer show in the system.

![image](https://user-images.githubusercontent.com/7606957/51696130-c0d09880-1fd2-11e9-88a6-5be6820512f6.png)

Console view:

![image](https://user-images.githubusercontent.com/7606957/51696204-e3fb4800-1fd2-11e9-8cf5-9c3cf8b14561.png)

**Comment by bormesh** [comment]
The problem for now is the armslen_comparison.xlsx file. The uploader only knows how to handle single sheet xlsx files (outside of the dashboard file). armslen_comparison is blowing up the whole job. I'll remove and reload your zip file and also add a fix so a single file can't break the whole data load.

**Comment by aprilhirsh** [comment]
oh my goodness, i'm so sorry i didn't realize that was in there :(
