### ISSUE TITLE
Overview tab- Workforce section incorrect header

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#21]
In the overview tab, the workforce section has the incorrect header. It reads 2012-2016 but should read 2013-2017.

![image](https://user-images.githubusercontent.com/7606957/52570862-62812380-2de2-11e9-9016-5f0cd020bc4b.png)

**Comment by bormesh** [comment]
Workforce is now updated with the correct dates on the overview tab.

**Comment by aprilhirsh** [comment]
Fixed
