### ISSUE TITLE
Equity tab- Make order of racial groups consistent

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#25]
Can we keep the order of the racial groups consistent? Right now, they are inconsistent. Let's order them as follows:

Non-hispanic Black
Non-hispanic White
Hispanic
Non-hispanic Asian
Non-hispanic other

Sometimes the groups are slightly different.

Black
White
Hispanic
Asian
Other

Let me know if this is something you need me to do.

**Comment by bormesh** [comment]
I'll set the order as above. If we update the meta data as disccused in #28 , then the groups should be consistent througout.

**Comment by bormesh** [comment]
Ok, on the tables the order is set as above. Once the meta descriptions are updated, it should look a lot better.

**Comment by bormesh** [comment]
Still need to update the charts with the ordering.

**Comment by bormesh** [comment]
Charts are now consistent as well.
