### ISSUE TITLE
Equity tab- Indent all sub-indicators

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#26]
Leave the leading indicator (indicator not broken out by racial group, circled in red in the picture below, place where the view chart function is) NOT indented, even in instances where it is a percent. This is different from the rest of the Progress Index where all percents are indented.
Then, indent all sub indicators (indicator broken out by racial group). These have the blue arrow in the example below.
Do this will all indicators, not just the one in the example below.
![image](https://user-images.githubusercontent.com/7606957/56586072-02121d80-65ad-11e9-9331-85256043d4f1.png)

**Comment by bormesh** [comment]
This is updated. I think leaving the indented text italicized is also nice. It doesn't match the style of the rest of the site, but should still be legible. 

Also, thanks for the descriptive graphic :)
