### ISSUE TITLE
Equity Tab- Table- Include only race label in sub indicators

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#28]
In the indented sub indicators, let's include only the race label, and not repeat the full indicator name. In the picture below, I cross out the full indicator name that we would leave out, including only the race label. We would not include the parenthesis.

Is this something we can solve by changing the meta data?

**Comment by bormesh** [comment]
Yes! this would be much better to do by changing the meta data. If this is fast, then that would be the desired method, as otherwise I have to write something to filter the names and find the race label.

Can you try a new data upload with the updated meta data? If not, let me know.

**Comment by aprilhirsh** [comment]
Before we try it, I have something called "chart label" in the meta data sheet. I'm guessing right now "variable description" feeds the name/label right now. Could that be changed to chart label just for the sub-indicators presented in the table?
![image](https://user-images.githubusercontent.com/7606957/57233979-ba988200-6fed-11e9-9f36-44b859068eaa.png)

**Comment by bormesh** [comment]
Ah, that works perfect! Sub-indicators on the table are now updated.
