### ISSUE TITLE
Overview tab- more progress metrics table doesn't load for City of Cleveland or Cuyahoga County geography

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#3]
In the overview tab, the "more progress metrics" table doesn't load for the City of Cleveland or the Cuyahoga County geography

![image](https://user-images.githubusercontent.com/7606957/51331652-33c49700-1a48-11e9-965a-5f609d93d065.png)

![image](https://user-images.githubusercontent.com/7606957/51331693-476ffd80-1a48-11e9-93a1-ff22858be1ec.png)

**Comment by aprilhirsh** [comment]
Is the 5 year change problem is a result of #20 ?

**Comment by bormesh** [comment]
Seems to be as 5 year change is now present.
