### ISSUE TITLE
Map and Table View- Year Labels Incorrect in all Multi-Year indicators

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#32]
In all of my spot checks of indicators, all of the multi-year indicators (where a set of multiple years makes up a single time point, ex- 2008-2012 make up one time point), the time points in the mapping and table functionality are incorrect. 

See #31  and #30 for specific examples in two indicators.

Let me know if you need me to list all of the effected indicators.

**Comment by bormesh** [comment]
Checked through -- the map and table observation tables should now be correct.
