### ISSUE TITLE
Incorrect year label in table in Health tab

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#36]
the first table in the health tab has the incorrect year label. it should be 2012-2016. Since there are two tables separating these indicators by data source, i'm not sure why this label is incorrect. it is correct in the CNP Dashboard Varlist. It would be nice if this were corrected before this version is pushed to production. 

![image](https://user-images.githubusercontent.com/7606957/58128639-1bc37680-7be6-11e9-8806-21c1a33042d4.png)

![image](https://user-images.githubusercontent.com/7606957/58128675-2bdb5600-7be6-11e9-9f97-4fbcc58c186f.png)

**Comment by aprilhirsh** [comment]
![image](https://user-images.githubusercontent.com/7606957/58255494-1fb4dd00-7d3b-11e9-9266-dbced83aaa69.png)

**Comment by bormesh** [comment]
Should now be correct
