### ISSUE TITLE
Equity tab- correct lead table year label

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#37]
I checked the Equity section after this last upload, realizing that these indicators are also in that section. I should have thought to do this earlier. Like the Health Tab, the equity tab also has mortality, infant mortality, and blood lead level all in one table under the year 2012-2016. We need mortality and infant mortality to be under a 2012-2016 heading, and blood lead level to be under one 2013-2017 heading. The estimates are now missing, I'm thinking because of the header issue.

![image](https://user-images.githubusercontent.com/7606957/58482672-cbd83880-812c-11e9-97e6-07e5c2f90e65.png)

When you navigate to the map function through the indicator by race, everything looks good. Same with the table.
![image](https://user-images.githubusercontent.com/7606957/58482692-d4307380-812c-11e9-9a31-09a56008b9d7.png)

![image](https://user-images.githubusercontent.com/7606957/58482704-d98dbe00-812c-11e9-8477-ac638f50b86c.png)

**Comment by bormesh** [comment]
Ok, the equity health table is also split now as well and years should be correct.

**Comment by bormesh** [comment]
Also, side comment -- if you give me @bormesh write access to this repository, then I can push the code here as well.
