### ISSUE TITLE
Health Section- data updated but header did not

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#39]
In the health metrics section, in the first table including life expectancy, mortality rate, and infant mortality rate, the data displaying appears correct for the 2014-2018 time period, but the header is the 2013-2017 time period.

![image](https://user-images.githubusercontent.com/7606957/81078539-6522d980-8ebc-11ea-93a2-8da788e7243b.png)

**Comment by bormesh** [comment]
This is fixed and updated
