### ISSUE TITLE
Progress Metrics tab- Sales data table not loading for City and County geography

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#4]
In the Progress Metrics tab, the 2016 and 2017 years are not loading in the sales data table for the City of Cleveland and Cuyahoga County geographies:

![image](https://user-images.githubusercontent.com/7606957/51332060-04faf080-1a49-11e9-956d-a720ea980726.png)

![image](https://user-images.githubusercontent.com/7606957/51332089-0fb58580-1a49-11e9-853d-a62c26183323.png)

**Comment by bormesh** [comment]
Cuyahoga County and Cleveland are now displaying. Still need to fix #1
