### ISSUE TITLE
Health section- elevated blood lead level table- data not found

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#40]
It looks like the elevated blood lead level table in the health section can't find the updated lead data. The lead indicator is 

_ebll_c1418

It **looks** like the table knows that- it lists the indicator correctly in the "i" icon. Not sure what else could be going on.

Maybe the data load process didn't find this table?

![image](https://user-images.githubusercontent.com/7606957/81080578-e0858a80-8ebe-11ea-8101-10a8161e3026.png)

**Comment by bormesh** [comment]
This is fixed
