### ISSUE TITLE
Education section- extra column in attendance rate table

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#41]
Not sure why there's an extra column in the attendance rate table. Other data appears to be loading correctly.
![image](https://user-images.githubusercontent.com/7606957/81085062-b46d0800-8ec4-11ea-83ad-d96a74ece50b.png)

**Comment by bormesh** [comment]
This is now resolved :

![image](https://user-images.githubusercontent.com/2038993/81976651-27931e80-9629-11ea-88c0-bdbca4af97c9.png)
