### ISSUE TITLE
Overview Tab- Incorrect Year Header

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#42]
The year header is incorrect for the second table, title "more progress metrics" in the overview tab. It should be 2014-2018.

![image](https://user-images.githubusercontent.com/7606957/83645162-26964280-a580-11ea-8cfa-a643cb3d77c9.png)

**Comment by aprilhirsh** [comment]
For clarity, all the values are correct and reflect the most recent time point ($718 is correct, $26,017 is correct), it's just the header should be 2014-2018

**Comment by bormesh** [comment]
The header is now updated to 2014-2018.
