### ISSUE TITLE
Overview tab- incorrect year header- stabilization

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#43]
There's an incorrect year header in the overview tab for the "stabilization" indicator. This indicator is an oddity in that we're providing 2019 data here where we mostly only provide data up to 2018 for the other indicators. Is it possible to display the 2019 data here?

![image](https://user-images.githubusercontent.com/7606957/83646686-fbacee00-a581-11ea-9bce-b6db25419bba.png)

**Comment by aprilhirsh** [comment]
Quick follow-up for clarity, the number (8,278) is correct and is for the 2019 year. It's just the header (2018) that's incorrect.

**Comment by bormesh** [comment]
The 2019 header date is now correct.
