### ISSUE TITLE
Overview tab- incorrect year header- health

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#44]
The year header for the health section/row is incorrect. It displays 2013-2017 but should display 2014-2018.

![image](https://user-images.githubusercontent.com/7606957/83646866-3a42a880-a582-11ea-90ea-791bc51bb1a4.png)

**Comment by aprilhirsh** [comment]
Value is correct for 2014-2018 time period, it's just the header that is incorrect.

**Comment by bormesh** [comment]
Updated -- 2014 - 2018 should now display.
