### ISSUE TITLE
Overview tab- education section- incorrect year header

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#46]
In the overview tab, the education section has an incorrect year header. The values are correct and reflect the 2018-2019 school year time period. The header is labeled 2017-2018.

![image](https://user-images.githubusercontent.com/7606957/83649281-01f09980-a585-11ea-89eb-9110322ac218.png)

**Comment by bormesh** [comment]
This is now updated.
