### ISSUE TITLE
Update CDC Service Area shapefile/boundaries

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#47]
Attached is the shapefile you can use to update the CDC service area boundaries for 2018 (that's what we're calling this).
[2019CDCServiceAreas_updated_20200103.zip](https://github.com/PovertyCenterCLE/Progress_Index_Bugs/files/4724108/2019CDCServiceAreas_updated_20200103.zip)

**Comment by bormesh** [comment]
This is now updated. Please double check that the shapes are correct -- but to my eyes, they look good!

**Comment by tsuichan** [comment]
Look correct to me.
