### ISSUE TITLE
Equity charts- n/a displays as 1,000,000

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#48]
The equity charts display an "n/a" value (the n/a value happens if the numbers are too low for us to calculate or display with confidence or without breaching confidentiality) as 1,000,000. Is there a way to have them not display? This skews the rest of the chart.

Cells with n/a values are unfortunately somewhat common in this section.

![image](https://user-images.githubusercontent.com/7606957/83651459-7f1d0e00-a587-11ea-9257-5e442475d37f.png)

**Comment by bormesh** [comment]
This is now fixed -- as Asian is 'n/a' I've left it out of the comparison chart (this goes for any time an indicator is n/a).
