### ISSUE TITLE
Progress Metrics tab- rental data, income data, poverty data not loading for City and County geographies

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#5]
In the Progress Metrics tab, the rental data, income data, and poverty data tables are not loading for the City and County geographies. The housing cost burden tables does not load for any geographies (documented in another issue).

![image](https://user-images.githubusercontent.com/7606957/51332471-ce71a580-1a49-11e9-9d2f-944adaabef6d.png)

![image](https://user-images.githubusercontent.com/7606957/51332504-daf5fe00-1a49-11e9-84b2-9e3a67b76f4d.png)

**Comment by bormesh** [comment]
Cuyahoga County and Cleveland are now displaying. Still need to fix #1
