### ISSUE TITLE
Equity section- city geography- education table- not displaying 2018-2019 school year

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#50]
At the city geography, in the Equity section, the education table is displaying 2017-2018 school year as the last school year available. It should display 2018-2019. 
This may be because we name the geography "cleveland metropolitan school district" in the data file instead of "city of cleveland." 
I will check in with Tsui on whether we can accurately rename this "city of cleveland" and then modify and upload the related data files.

**Comment by aprilhirsh** [comment]
Same issue in education section

![image](https://user-images.githubusercontent.com/7606957/83663091-610ada00-a596-11ea-8668-a3e09487218c.png)

**Comment by tsuichan** [comment]
Displaying data for 6 school years after April modified the file.  Data for 2013-2014 school year should be removed.

**Comment by tsuichan** [comment]
Under Education, can "Number of quality pre-school slots" has it own box similar to "attendance rate"?  It is creating a blank column for the other education indicators when they don't have the same time frame.

**Comment by bormesh** [comment]
This is updated so "Number of quality pre-school slots" now has it's own table -- which means it doesn't cause the extra blank column for the tables above.
