### ISSUE TITLE
Workforce- LEHD- Data check

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#51]
The indicators-- number living in neighborhood but working outside, and number employed in neighborhood but living outside, seem incorrect to me, at least at the City and County levels. Checking them with Tsui.

![image](https://user-images.githubusercontent.com/7606957/83664015-6f0d2a80-a597-11ea-9379-cb59a4dab366.png)

**Comment by tsuichan** [comment]
The numbers are correct.
