### ISSUE TITLE
Community section - Computer and Internet Access - Incorrect year header

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#52]
Computer and Internet Access section should only have two time periods like the ACS data.
2009-2013 and 2014-2018

Computer and Internet Access indicators were repeated in the Voter Participation section.  They  should be removed.

**Comment by bormesh** [comment]
Hmm, there might be a data load problem here then, as it looks like we're only getting the 2014-2018 data. I'll look back into this. 

The duplication is resolved as well.

**Comment by tsuichan** [comment]
You are correct.  The variables under Computer and Internet Access are not available in 2009-2013 ACS.  Can you just put 2014-2018 for these variables?  Thanks!
