### ISSUE TITLE
Added the last two missing tabs -- Tsui or April Please check

### ISSUE THREAD

**Issue by bormesh** [PovertyCenterCLE/Progress_Index_Bugs#55]
Hi Tsui,

we had two more tabs, I believe, that we needed to add. I've added the 'Households and Mobility' tab as well as the 'Income and Poverty' tab.

These new tabs need checks to make sure all the data looks good. 

Thanks!
Mobility - http://profiles.216software.com/#/mobility?location_uuid=a858a6dc-2d47-4417-a55c-3674f4fd32e4&expand_everything=undefined

Income - http://profiles.216software.com/#/income-poverty?location_uuid=a858a6dc-2d47-4417-a55c-3674f4fd32e4

**Comment by tsuichan** [comment]
Looks good.  For average household size and average family size, can you remove % next to the numbers?  This is a special case.  Thanks!
