### ISSUE TITLE
Add % change for Housing Cost Burden Data

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#56]
Please add the column "% change" for indicators under Housing Cost Burden Data in both Progress Metrics and Equity.  We have data for two time periods this year.  Thanks!

**Comment by bormesh** [comment]
The %change is now there for the Housing Cost Burden Data

**Comment by tsuichan** [comment]
Can you also add % change for Housing Cost Burden Data for the Progress Metrics section? Thanks.

**Comment by bormesh** [comment]
No problem -- added that as well :)

**Comment by tsuichan** [comment]
Great. I can close this now.
