### ISSUE TITLE
Health Metrics - Blood Lead number format

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#57]
Can you add % and round the number to one decimal place for the blood lead indicator?  Thanks!

**Comment by bormesh** [comment]
This is now updated:
![image](https://user-images.githubusercontent.com/2038993/87577022-8aa93c00-c6d2-11ea-9300-ec8082b3bbd3.png)

**Comment by tsuichan** [comment]
Perfect.  Thanks!
