### ISSUE TITLE
 Location Drop Down Menu - Clean up old and duplicate names

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#60]
Please remove the followings from the Location list:

Buckeye Area Dev Corp.
Buckeye Shaker Square Dev Corp.  (the one without a period after "Dev")
Burton Bell Carr Dev. Corp.
Metro West Dev. Corp.

Under neighborhood level, remove the followings:
Unknown neighborhood
_Cuyahoga
__Cleveland Municipal School District
Cleveland Municipal School District

Also under neighborhood level, can you change "Cleveland city" to "Cleveland City" and "Cuyahoga" to "Cuyahoga County"?  I would prefer they don't show up in the drop down menu for neighborhood level.  Let me know what is the best way to do this.  Thanks.

**Comment by bormesh** [comment]
These are now updated.

**Comment by tsuichan** [comment]
Please remove the followings:

Collinwood Nottingham Villages Dev. Corp.
Cleveland City
Suburb
