### ISSUE TITLE
Add tables for new indicators by race

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#61]
Here are the new indicators need to be broken out by race (see first worksheet on new.indicators.draft.placement.20200415.xlsx from April).

Population -- Native/foreign born population
Households, Families & Mobility -- Persons living in the same house/different house 1 year ago
Income and Poverty -- Households received Food Stamps/SNAP
Workforce -- Workers by method of transportation to work 

There will be a lot of indicators on these tabs.  Can we make them collapsible like the Equity section?

**Comment by bormesh** [comment]
These are all now added. I'll still make each of the sections collapsible as at the moment, it's pretty big!

**Comment by bormesh** [comment]
I've added show / hide for all tables mentioned here except for Income and Poverty, as that page is not too long at the moment.
