### ISSUE TITLE
Labels for Lead Data Under Equity (Health Data) and Health Sections Not Updated

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#62]
I uploaded the revised labels for the blood lead variables but I can't see the change after refresh the page.  However, changes for other sections worked.  I don't know why.

**Comment by bormesh** [comment]
On the CNP Dashboard Variable list, the blood level variables should strip off the 1418 -- so 

"_ebll_c1418" should be "_ebll_c" -- If you reload the file with that change, you should see the descriptions updated correctly.
