### ISSUE TITLE
Households and Mobility - Race Labels Disappear

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#63]
The race labels under "Persons lived in same house 1 year ago" and "Persons lived in different house 1 year ago" were there before.  Now they disappear.  Please check.  Thanks!

**Comment by bormesh** [comment]
It looks like these variables don't have the column 'Chart Label' filled out on the CNP Dashboard Varlist.xlsx file. If you update there and then redo the data load, the labels will be correct :)
