### ISSUE TITLE
About Page - Update Contact Info

### ISSUE THREAD

**Issue by tsuichan** [PovertyCenterCLE/Progress_Index_Bugs#66]
Please update the contact info in the "About" page.  Thanks!

Justin D. Fleming
Director of Real Estate and General Counsel
President, Land Assembly for Neighborhood Development
Cleveland Neighborhood Progress
jfleming@clevelandnp.org

April Urban
Director of Community Responsive Analytics
Center on Urban Poverty and Community Development
april.urban@case.edu

**Comment by tsuichan** [comment]
Can you remove Justin D. Fleming in the second line and delete "Manager of CDC Advancemenident, Land Assembly for Neighborhood Development"?  Thanks!

Justin D. Fleming
Justin D. Fleming Director of Real Estate and General Counsel
Cleveland Neighborhood Progress
Manager of CDC Advancemenident, Land Assembly for Neighborhood Development
jfleming@clevelandnp.org

**Comment by bormesh** [comment]
This is now updated.
