### ISSUE TITLE
Stabilization tab- 2016 and 2017 data not displaying for City and County geographies

### ISSUE THREAD

**Issue by aprilhirsh** [PovertyCenterCLE/Progress_Index_Bugs#9]
In the stabilization tab, the 2016 and 2017 years are not displaying for the City and County geographies

![image](https://user-images.githubusercontent.com/7606957/51333421-a4b97e00-1a4b-11e9-97ef-a9265721b27f.png)

![image](https://user-images.githubusercontent.com/7606957/51333440-b00ca980-1a4b-11e9-9f13-7cbc44facb11.png)

**Comment by bormesh** [comment]
Cleveland and Cuyahoga County now display correctly for Stabilization tab
